#from . import res_partner
#from . import sale
#from . import project
#from . import res_company
#from . import mail_mail
from . import crm_helpdesk
from . import crm_helpdesk_category
#from . import mail_compose_message
#from . import mail_followers
#from . import mail_thread
